on:
  push:
    branches:
      - main
  
permissions:
  contents: write
  pull-requests: write
  
name: release-please
  
jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: jimeh/release-please-manifest-action@v1
        with:
          app-id: ${{ secrets.RELEASE_BOT_APP_ID }}
          private-key: ${{ secrets.RELEASE_BOT_PRIVATE_KEY }}
