on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

name: release-please

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v4
        id: release
        with:
          # This is a personal access token (PAT) which has been
          # configured as a GitHub action secret.
          token: ${{ secrets.GITHUB_TOKEN }}
          # This release type is for repos with a version.txt and
          # a CHANGELOG.md.
          release-type: simple
        continue-on-error: true
          
      - name: Echo release outputs
        if: ${{ steps.release.outputs }}
        run: echo '${{ toJson(steps.release) }}'
        continue-on-error: true
      # - uses: actions/create-release@v1
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #   with:
      #     tag_name: 'v${{steps.release.outputs.major}}'
      #     release_name: 'v${{steps.release.outputs.major}}'
      #     draft: false
      #     prerelease: false


